// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProfitOrLossBackend.Models;

#nullable disable

namespace ProfitOrLossBackend.Migrations
{
    [DbContext(typeof(ProfitOrLossContext))]
    partial class ProfitOrLossContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProfitOrLossBackend.Models.FinancialYear", b =>
                {
                    b.Property<int>("FinancialYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FinancialYearId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinancialYearId"));

                    b.Property<string>("FinancialYearName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FinancialYearName");

                    b.HasKey("FinancialYearId");

                    b.ToTable("FinancialYear");
                });

            modelBuilder.Entity("ProfitOrLossBackend.Models.ShareCompany", b =>
                {
                    b.Property<int>("ShareCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShareCompanyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShareCompanyId"));

                    b.Property<string>("ShareCompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ShareCompanyName");

                    b.HasKey("ShareCompanyId");

                    b.ToTable("ShareCompany");
                });
#pragma warning restore 612, 618
        }
    }
}
